[template]

src = "nginx.tmpl"
dest = "/tmp/nginx.conf"
keys = [ "/apps" ]
owner = "root"
mode = "0644"
#check_cmd = "/usr/sbin/nginx -t"
# TODO remove sed rewriting and pull app names from etcd
reload_cmd = "/bin/bash -c 'sed \"s/\\/apps\\///g\" /tmp/nginx.conf > /etc/nginx/sites-available/default && service nginx reload'"
