#!/bin/sh
# Usage: opshell create MYAPP
# TODO APP should default to name of current dir/repo?
APP=$1
if [ ! -d ~/$APP.git ]; then
mkdir ~/$APP.git
sudo mkdir -p /data/apps/$APP
sudo chmod 777 /data/apps/$APP
cd ~/$APP.git
git init --bare
cat << EOF > hooks/post-receive
#!/bin/sh
git --work-tree=/data/apps/$APP clean -fd --exclude node_modules
git --work-tree=/data/apps/$APP checkout --force
docker run --rm -v /data/apps/$APP:/data/apps/$APP app bash -c 'cd /data/apps/$APP; npm install --production; npm prune --production'
sudo chown -R core:core /data/apps/$APP/node_modules
fleetctl stop ~/instances/* && fleetctl start ~/instances/*
EOF
chmod +x hooks/post-receive
cat << EOF > /data/apps/$APP/index.js
require('http').createServer(function(req, res) {
  res.writeHead(200, {"Content-Type":"text/plain; charset=utf-8"});
  res.end('Hello $APP!\n');
}).listen(8080);
EOF
fi
# TODO opshell scale 1
# TODO git remote add?